spring.application.name=biblioteca-api

# Conexión a MongoDB Atlas (Reemplaza con tus credenciales reales)
spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:TuPassword@biblioteca-cluster.ab1cd.mongodb.net/biblioteca_db?retryWrites=true&w=majority
spring.data.mongodb.database=biblioteca_db

# Puerto del Servidor local
server.port=8080