spring.application.name=biblioteca-api

# Conexión a MongoDB Atlas (Reemplaza con tus credenciales reales)
spring.data.mongodb.uri=mongodb+srv://barusu:TU_CONTRASEÑA_AQUI@barusu.pwqggaw.mongodb.net/?appName=barusu
spring.data.mongodb.database=biblioteca_db

# Puerto del Servidor local
server.port=8080